diff --git a/Makefile b/Makefile
index e5b17fd..ff1c3db 100644
--- a/Makefile
+++ b/Makefile
@@ -2,11 +2,10 @@ MODULE_NAME = gslx680_ts_acpi
 
 #CROSS_COMPILE ?= arm-linux-gnueabihf-
 #ARCH ?= arm
-ARCH := $(shell uname -m | sed -e s/i.86/i386/)
-KVER := $(shell uname -r)
-KSRC := /lib/modules/$(KVER)/build
+KSRC := $(KERNEL_SRC)
 PWD = $(shell pwd)
-MODDESTDIR := /lib/modules/$(KVER)/kernel/drivers/input/touchscreen
+#MODDESTDIR := $(INSTALL_MOD_PATH)/lib/modules/$(KVER)/kernel/drivers/input/touchscreen
+MODDESTDIR ?= $(INSTALL_MOD_PATH)
 
 obj-m += gslx680_ts_acpi.o
 
@@ -15,15 +14,13 @@ obj-m += gslx680_ts_acpi.o
 all: modules
 
 modules:
-	make -C $(KSRC) ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) M=$(PWD) modules
+	$(MAKE) -C $(KSRC) M=$(PWD) modules
 
-install:
-	install -p -m 644 $(MODULE_NAME).ko  $(MODDESTDIR)
-	/sbin/depmod -a $(KVER)
+modules_install install:
+	$(MAKE) -C $(KERNEL_SRC) M=$(PWD) modules_install INSTALL_MOD_PATH=$(MODDESTDIR)
 
 uninstall:
 	rm -f $(MODDESTDIR)/$(MODULE_NAME).ko
-	/sbin/depmod -a $(KVER)
 
 clean:
-	make -C $(KSRC) ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) M=$(PWD) clean
+	$(MAKE) -C $(KSRC) ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) M=$(PWD) clean
